#!/usr/bin/env bash
# Install the local-auditor skill by SYMLINK, so `git pull` is the whole update.
#
# Why symlinks and not copies: a copied install drifts. The forwarders below exec
# the scripts inside the installed skill, so linking the skill directory updates
# the skill AND the CLIs together and they cannot diverge.
#
# Windows (Git Bash): a real symlink needs Developer Mode or an elevated shell.
# When one cannot be made the skill is COPIED instead, with a warning -- re-run
# this script after every `git pull` in that case.
#
# The config is seeded from config.example ONCE and never overwritten.
#
#   --no-preflight   skip the server/python/claude checks
#   --force          replace a non-symlink skill directory instead of backing it up
#   --uninstall      remove the skill and the two commands (keeps your config)
set -u
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NO_PREFLIGHT=0; FORCE=0; UNINSTALL=0
for a in "$@"; do
  case "$a" in
    --no-preflight) NO_PREFLIGHT=1 ;;
    --force)        FORCE=1 ;;
    --uninstall)    UNINSTALL=1 ;;
    -h|--help)      sed -n '2,16p' "$0"; exit 0 ;;
    *) echo "install.sh: unknown option: $a (see --help)" >&2; exit 2 ;;
  esac
done

say()  { printf 'install: %s\n' "$*"; }
die()  { printf 'install: %s\n' "$*" >&2; exit 1; }

is_windows() {
  case "$(uname -s 2>/dev/null)" in MINGW*|MSYS*|CYGWIN*) return 0 ;; esac
  return 1
}

# Where Claude Code looks for skills: $CLAUDE_CONFIG_DIR when set; on Windows the
# native claude reads %USERPROFILE%\.claude, which need not be Git Bash's $HOME.
if [ -n "${CLAUDE_CONFIG_DIR:-}" ]; then
  CLAUDE_DIR="$CLAUDE_CONFIG_DIR"
elif is_windows && [ -n "${USERPROFILE:-}" ] && command -v cygpath >/dev/null 2>&1; then
  CLAUDE_DIR="$(cygpath -u "$USERPROFILE")/.claude"
else
  CLAUDE_DIR="$HOME/.claude"
fi
SKILL_LINK="$CLAUDE_DIR/skills/local-auditor"
BIN_DIR="$HOME/.local/bin"
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/qwen-agent"
CONFIG="$CONFIG_DIR/config"

if [ "$UNINSTALL" -eq 1 ]; then
  if [ -L "$SKILL_LINK" ]; then
    rm -f "$SKILL_LINK" && say "removed $SKILL_LINK"
  elif [ -f "$SKILL_LINK/.installed-copy" ]; then
    rm -rf "$SKILL_LINK" && say "removed the copied skill at $SKILL_LINK"
  elif [ -e "$SKILL_LINK" ]; then
    say "left $SKILL_LINK alone: this script did not install it"
  fi
  for c in qwen-agent qwen-sweep; do
    if [ -f "$BIN_DIR/$c" ] && grep -q 'Generated by install.sh' "$BIN_DIR/$c"; then
      rm -f "$BIN_DIR/$c" && say "removed $BIN_DIR/$c"
    fi
  done
  say "kept $CONFIG and past sweep runs; delete them yourself if you want them gone"
  exit 0
fi

link_dir() {  # link_dir <target-dir> <linkname>
  local target="$1" name="$2" bak
  [ -d "$target" ] || die "missing in repo: $target"
  if [ -L "$name" ]; then
    rm -f "$name"
  elif [ -e "$name" ]; then
    if [ -f "$name/.installed-copy" ] || [ "$FORCE" -eq 1 ]; then
      rm -rf "$name"
    else
      bak="$name.bak-$(date -u +%Y%m%dT%H%M%S)"
      mv "$name" "$bak" || die "cannot move $name aside"
      say "existing $name was a real directory; moved to $bak"
    fi
  fi
  mkdir -p "$(dirname "$name")"
  if [ "${QWEN_INSTALL_FORCE_COPY:-0}" != 1 ]; then
    if is_windows; then
      # Without nativestrict, Git Bash's (and Cygwin's) ln silently makes a copy
      # or a link that native programs such as claude cannot follow.
      MSYS=winsymlinks:nativestrict CYGWIN=winsymlinks:nativestrict ln -s "$target" "$name" 2>/dev/null
    else
      ln -s "$target" "$name"
    fi
  fi
  if [ -L "$name" ]; then
    say "linked $name -> $target"
    return 0
  fi
  rm -rf "$name"
  cp -R "$target" "$name" || die "could not link or copy $target to $name"
  : > "$name/.installed-copy"
  say "WARNING: symlinks are unavailable here, so the skill was COPIED to $name."
  say "         Re-run install.sh after every git pull (or enable Windows Developer Mode)."
}

forwarder() {  # forwarder <name> <script-inside-skill>
  local name="$BIN_DIR/$1" script="$SKILL_LINK/$2"
  cat > "$name" <<FWD
#!/usr/bin/env bash
# Generated by install.sh. Execs the script inside the installed skill, so the
# CLI and the skill can never drift apart.
exec bash "$script" "\$@"
FWD
  chmod +x "$name"
  say "wrote $name"
}

mkdir -p "$(dirname "$SKILL_LINK")" "$CONFIG_DIR" "$BIN_DIR"
link_dir "$REPO/skill/local-auditor" "$SKILL_LINK"

if [ -L "$CONFIG" ] && [ ! -e "$CONFIG" ]; then
  say "WARNING: $CONFIG was a broken symlink; replacing it with config.example"
  rm -f "$CONFIG"
fi
if [ -e "$CONFIG" ]; then
  say "kept existing $CONFIG"
else
  cp "$REPO/config.example" "$CONFIG" || die "cannot write $CONFIG"
  say "wrote $CONFIG"
fi

forwarder qwen-agent qwen-agent.sh
forwarder qwen-sweep qwen-sweep.sh

case ":$PATH:" in
  *":$BIN_DIR:"*) ;;
  *) say "WARNING: $BIN_DIR is not on PATH — add it or the commands will not resolve" ;;
esac

if [ "$NO_PREFLIGHT" -eq 1 ]; then
  say "skipped preflight (--no-preflight)"
  exit 0
fi
if cmp -s "$CONFIG" "$REPO/config.example"; then
  say "installed. Next: set QWEN_BASE_URL in $CONFIG, then run: qwen-agent --preflight-only"
  exit 0
fi

# Preflight by RUNNING things, never by `which`. Delegated to the CLI so there is
# exactly one implementation of these checks.
say "running preflight..."
bash "$SKILL_LINK/qwen-agent.sh" --preflight-only
rc=$?
case "$rc" in
  0) say "install complete." ;;
  3) die "installed, but the server check failed (rc=3): start the server, or fix QWEN_BASE_URL / QWEN_MODEL / QWEN_API_KEY in $CONFIG" ;;
  8) die "installed, but a prerequisite is missing (rc=8): install Claude Code and Python 3.8+, or set QWEN_CLAUDE_BIN / QWEN_PYTHON in $CONFIG" ;;
  *) die "installed, but preflight failed (rc=$rc) -- see the message above" ;;
esac
